apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: order-service-app
          image: IMAGE_URL/order-service:TAG
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "50m"
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: eureka_server_url
                  name: eureka-cm
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: config_server_url
                  name: config-cm
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: mysql_url
                  name: mysql-cm

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
    - port: 80
      targetPort: 8084
